/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultInt32 } from '../models';
import { CsForTestingInput } from '../models';
/**
 * CsForTestingApi - axios parameter creator
 * @export
 */
export const CsForTestingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   结果是偶数返回0  结果是奇数返回大于0
         * @param {CsForTestingInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCsForTestingCeshi2Post: async (body?: CsForTestingInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/csForTesting/ceshi2`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前加了Get的系统默认为get接口
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCsForTestingCeshiGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/csForTesting/ceshi`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前没有加任何前缀的默认为post接口
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCsForTestingCeshiPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/csForTesting/ceshi`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CsForTestingApi - functional programming interface
 * @export
 */
export const CsForTestingApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   结果是偶数返回0  结果是奇数返回大于0
         * @param {CsForTestingInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCsForTestingCeshi2Post(body?: CsForTestingInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultInt32>>> {
            const localVarAxiosArgs = await CsForTestingApiAxiosParamCreator(configuration).apiCsForTestingCeshi2Post(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前加了Get的系统默认为get接口
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCsForTestingCeshiGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultInt32>>> {
            const localVarAxiosArgs = await CsForTestingApiAxiosParamCreator(configuration).apiCsForTestingCeshiGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前没有加任何前缀的默认为post接口
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCsForTestingCeshiPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultInt32>>> {
            const localVarAxiosArgs = await CsForTestingApiAxiosParamCreator(configuration).apiCsForTestingCeshiPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CsForTestingApi - factory interface
 * @export
 */
export const CsForTestingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   结果是偶数返回0  结果是奇数返回大于0
         * @param {CsForTestingInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCsForTestingCeshi2Post(body?: CsForTestingInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultInt32>> {
            return CsForTestingApiFp(configuration).apiCsForTestingCeshi2Post(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前加了Get的系统默认为get接口
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCsForTestingCeshiGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultInt32>> {
            return CsForTestingApiFp(configuration).apiCsForTestingCeshiGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前没有加任何前缀的默认为post接口
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCsForTestingCeshiPost(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultInt32>> {
            return CsForTestingApiFp(configuration).apiCsForTestingCeshiPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CsForTestingApi - object-oriented interface
 * @export
 * @class CsForTestingApi
 * @extends {BaseAPI}
 */
export class CsForTestingApi extends BaseAPI {
    /**
     * 
     * @summary 测试  无实际意义配合web集成测试dome用   结果是偶数返回0  结果是奇数返回大于0
     * @param {CsForTestingInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CsForTestingApi
     */
    public async apiCsForTestingCeshi2Post(body?: CsForTestingInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultInt32>> {
        return CsForTestingApiFp(this.configuration).apiCsForTestingCeshi2Post(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前加了Get的系统默认为get接口
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CsForTestingApi
     */
    public async apiCsForTestingCeshiGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultInt32>> {
        return CsForTestingApiFp(this.configuration).apiCsForTestingCeshiGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 测试  无实际意义配合web集成测试dome用   注意：方法前没有加任何前缀的默认为post接口
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CsForTestingApi
     */
    public async apiCsForTestingCeshiPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultInt32>> {
        return CsForTestingApiFp(this.configuration).apiCsForTestingCeshiPost(options).then((request) => request(this.axios, this.basePath));
    }
}
