/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ErrorLevels } from './error-levels';
 /**
 * 
 *
 * @export
 * @interface TemplateErrorInfo
 */
export interface TemplateErrorInfo {

    /**
     * @type {ErrorLevels}
     * @memberof TemplateErrorInfo
     */
    errorLevel?: ErrorLevels;

    /**
     * @type {string}
     * @memberof TemplateErrorInfo
     */
    columnName?: string | null;

    /**
     * @type {string}
     * @memberof TemplateErrorInfo
     */
    requireColumnName?: string | null;

    /**
     * @type {string}
     * @memberof TemplateErrorInfo
     */
    message?: string | null;
}
