/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsDeliveryDollyOutput
 */
export interface WmsDeliveryDollyOutput {

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    id?: number;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    deliveryId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    sysNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    workOrderId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    workOrderNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    warehouseId?: number | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    warehouseAreaId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    warehouseAreaCode?: string | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    warehouseLocationId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    warehouseLocationCode?: string | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    targetWarehouseAreaId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    targetWarehouseAreaCode?: string | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    targetWarehouseLocationId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    targetWarehouseLocationCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    rowNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    batchNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    qty?: number | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    deliveryQty?: number | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    dollyQty?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    dollyNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    skuName?: string | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    spec?: string | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsDeliveryDollyOutput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsDeliveryDollyOutput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsDeliveryDollyOutput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsDeliveryDollyOutput
     */
    updateTime?: Date | null;
}
