/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WmsAdjustmentDetailAddInput } from './wms-adjustment-detail-add-input';
 /**
 * 
 *
 * @export
 * @interface WmsAdjustmentAddInput
 */
export interface WmsAdjustmentAddInput {

    /**
     * @type {number}
     * @memberof WmsAdjustmentAddInput
     */
    id?: number;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    adjustmentNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    sysNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentAddInput
     */
    customerId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    customerName?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentAddInput
     */
    warehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    warehouseName?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentAddInput
     */
    status?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    type?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    adjustmentReason?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAdjustmentAddInput
     */
    adjustmentTime?: Date | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentAddInput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAdjustmentAddInput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentAddInput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentAddInput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAdjustmentAddInput
     */
    updateTime?: Date | null;

    /**
     * @type {Array<WmsAdjustmentDetailAddInput>}
     * @memberof WmsAdjustmentAddInput
     */
    adjustmentDetail?: Array<WmsAdjustmentDetailAddInput> | null;
}
