/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsCheckDetailPageInput
 */
export interface WmsCheckDetailPageInput {

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof WmsCheckDetailPageInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof WmsCheckDetailPageInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof WmsCheckDetailPageInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof WmsCheckDetailPageInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof WmsCheckDetailPageInput
     */
    descStr?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailPageInput
     */
    checkId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailPageInput
     */
    checkNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailPageInput
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailPageInput
     */
    lpn?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailPageInput
     */
    isDifference?: number | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailPageInput
     */
    isDeal?: number | null;
}
