/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsAsnDetail
 */
export interface WmsAsnDetail {

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    id: number;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    asnId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    asnNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    customerId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    rowNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    orderLineId?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    shipmentNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    poNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    poOrderType?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    authorizationStatus?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    poLineNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    tpFlag?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    lineType?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    shipmentNum?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    deliveryDetailId?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    omLineId?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    lineStatus?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    scheduleShipDate?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    dueDate?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    quantity?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    cancelFlag?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    receivingRoutingId?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    lpnNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    boxNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    batchNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    qtyExpected?: number | null;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    qtyReceived?: number | null;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    qtyShelf?: number | null;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    isSample: number;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    skuType?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    skuName?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    spec?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAsnDetail
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsAsnDetail
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnDetail
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAsnDetail
     */
    updateTime?: Date | null;
}
