/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WmsCheckDetailDto } from './wms-check-detail-dto';
 /**
 * 
 *
 * @export
 * @interface WmsCheckAddInput
 */
export interface WmsCheckAddInput {

    /**
     * @type {number}
     * @memberof WmsCheckAddInput
     */
    id: number;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    checkNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    sysNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckAddInput
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsCheckAddInput
     */
    warehouseId?: number | null;

    /**
     * @type {any}
     * @memberof WmsCheckAddInput
     */
    checkDate?: any | null;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    type?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckAddInput
     */
    isDifference: number;

    /**
     * @type {number}
     * @memberof WmsCheckAddInput
     */
    isDeal: number;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckAddInput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsCheckAddInput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsCheckAddInput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsCheckAddInput
     */
    updateTime?: Date | null;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    customerName?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckAddInput
     */
    warehouseName?: string | null;

    /**
     * @type {Array<WmsCheckDetailDto>}
     * @memberof WmsCheckAddInput
     */
    checkDetails?: Array<WmsCheckDetailDto> | null;
}
