/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsInventoryHistoryOutput
 */
export interface WmsInventoryHistoryOutput {

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    id?: number;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    batchNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    customerId?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    customerName?: string | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseName?: string | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseAreaId?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseAreaCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseAreaName?: string | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseLocationId?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseLocationCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    warehouseLocationName?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    lpn?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    serialNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    qty?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    relationNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    relationDetailId?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    boxNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    spec?: string | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    oprType?: string | null;

    /**
     * @type {Date}
     * @memberof WmsInventoryHistoryOutput
     */
    oprTm?: Date | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsInventoryHistoryOutput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsInventoryHistoryOutput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsInventoryHistoryOutput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsInventoryHistoryOutput
     */
    updateTime?: Date | null;
}
