/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsCustomerDto
 */
export interface WmsCustomerDto {

    /**
     * @type {number}
     * @memberof WmsCustomerDto
     */
    id?: number;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    shortName?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    legalPerson?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    bank?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    account?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    taxId?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    invoiceTitle?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    province?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    city?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    address?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    postcode?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof WmsCustomerDto
     */
    status?: number | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    type?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    creditLine?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    contactPerson?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    mobileNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsCustomerDto
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsCustomerDto
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsCustomerDto
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCustomerDto
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsCustomerDto
     */
    updateTime?: Date | null;
}
