/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsProductUpdateInput
 */
export interface WmsProductUpdateInput {

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    id: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    supplierId?: number | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    supplierCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    status?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    enabledFlag?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    kitFlag?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    organizationId?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    itemId?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    skuName?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    itemNameEn?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    type?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    skuClassification?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    skuGroup?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    shortNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    skuReplaced?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    receivingRoutingId?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    planningMakeBuyCodeMir?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    boxGroup?: string | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    price?: number | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    volume?: number | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    weight?: number | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    length?: number | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    height?: number | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    width?: number | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    skuFamily?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    customerChartNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    unitTransFactor?: string | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isValidityTermAd: number;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    isBatchAd: string;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isSeqAd: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isQa: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isOffShelf: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isSort: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isDelivery: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isOrderPull: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isKbPull: number;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    isMarket: number;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    inboundType?: string | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    minCount?: number | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    maxCount?: number | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsProductUpdateInput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsProductUpdateInput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsProductUpdateInput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsProductUpdateInput
     */
    updateTime?: Date | null;
}
