/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsAdjustmentDetailAddInput
 */
export interface WmsAdjustmentDetailAddInput {

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    adjustmentNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    sysNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseName?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    skuName?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    batchNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    customerBatchNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    boxNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    fromLpn?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    lotNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    toLpn?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseAreaId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseAreaCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseAreaName?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseLocationId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseLocationCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    warehouseLocationName?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentDetailAddInput
     */
    targetWarehouseAreaId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    targetWarehouseAreaCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    targetWarehouseAreaName?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentDetailAddInput
     */
    targetWarehouseLocationId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    targetWarehouseLocationCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    targetWarehouseLocationName?: string | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentDetailAddInput
     */
    oldQty?: number | null;

    /**
     * @type {number}
     * @memberof WmsAdjustmentDetailAddInput
     */
    adjustmentQty?: number | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    fromSkuClassification?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    toSkuClassification?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    spec?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    adjustmentreason?: string | null;

    /**
     * @type {string}
     * @memberof WmsAdjustmentDetailAddInput
     */
    remark?: string | null;
}
