/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsCheckDetailDto
 */
export interface WmsCheckDetailDto {

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    id?: number;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    checkId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    checkNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    sysNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    warehouseId?: number | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    warehouseAreaId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    warehouseAreaCode?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    warehouseLocationId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    warehouseLocationCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    lpn?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    batchNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    boxNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    spec?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    skuClassification?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    checkQty?: number | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    actualQty?: number | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    isDifference?: number;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    isDeal?: number;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsCheckDetailDto
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsCheckDetailDto
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsCheckDetailDto
     */
    updateTime?: Date | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    customerName?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    warehouseName?: string | null;

    /**
     * @type {string}
     * @memberof WmsCheckDetailDto
     */
    lineStatus?: string | null;
}
