/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsOutboundOutput
 */
export interface WmsOutboundOutput {

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    id?: number;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    sysOutboundNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    externOrderNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    warehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    warehouseCode?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    targetWarehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    targetWarehouseCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    type?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    status?: number | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundOutput
     */
    orderTime?: Date | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    orgId?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    province?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    city?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    district?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    address?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    contactPerson?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    mobileNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    logisticsName?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    vehicleNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    detailCount?: number | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    ownerId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    customerCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    customerName?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    lineCode?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundOutput
     */
    sendDate?: Date | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundOutput
     */
    arriveDate?: Date | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundOutput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsOutboundOutput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundOutput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundOutput
     */
    updateTime?: Date | null;
}
