/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsOutboundDetail
 */
export interface WmsOutboundDetail {

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    id: number;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    outboundId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    sysOutboundNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    externOrderNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    warehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    rowNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    orderLineId?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    shipmentNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    lineStatus?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    sku?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    customItemNo?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    skuName?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    skuClassification?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    orderQty?: number | null;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    allocatedQty?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    boxNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    batchNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    spec?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    ownerId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    lpn?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    acceptAdress?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    promiseDate?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    requestDate?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    scheduleShipDate?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    omLineId?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    deliveryDetailId?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundDetail
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsOutboundDetail
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundDetail
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundDetail
     */
    updateTime?: Date | null;
}
