/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsOutboundInput
 */
export interface WmsOutboundInput {

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof WmsOutboundInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof WmsOutboundInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof WmsOutboundInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof WmsOutboundInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof WmsOutboundInput
     */
    descStr?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    sysOutboundNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    externOrderNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    warehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    warehouseCode?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    targetWarehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    targetWarehouseCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    type?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    status?: number | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundInput
     */
    orderTime?: Date | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    orgId?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    province?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    city?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    district?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    address?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    contactPerson?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    mobileNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    logisticsName?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    vehicleNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    detailCount?: number | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    ownerId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    customerCode?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    customerName?: string | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    lineCode?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundInput
     */
    sendDate?: Date | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundInput
     */
    arriveDate?: Date | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundInput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsOutboundInput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsOutboundInput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsOutboundInput
     */
    updateTime?: Date | null;

    /**
     * @type {Array<Date>}
     * @memberof WmsOutboundInput
     */
    orderTimeRange?: Array<Date> | null;

    /**
     * @type {Array<Date>}
     * @memberof WmsOutboundInput
     */
    sendDateRange?: Array<Date> | null;

    /**
     * @type {Array<Date>}
     * @memberof WmsOutboundInput
     */
    arriveDateRange?: Array<Date> | null;

    /**
     * @type {Array<Date>}
     * @memberof WmsOutboundInput
     */
    createTimeRange?: Array<Date> | null;

    /**
     * @type {Array<Date>}
     * @memberof WmsOutboundInput
     */
    updateTimeRange?: Array<Date> | null;
}
