/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WmsWarehouseLocation
 */
export interface WmsWarehouseLocation {

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    id: number;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    warehouseId?: number;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    warehouseName?: string | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    areaId?: number | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    areaName?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    locationName?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    locationNameEn?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    enabledFlag?: string | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    status?: number | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    type?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    classification?: string | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    isMultiSku: number;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    level?: string | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    weight?: number | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    length?: number | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    width?: number | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    height?: number | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    coordX?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    coordY?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    coordZ?: string | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsWarehouseLocation
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsWarehouseLocation
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsWarehouseLocation
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsWarehouseLocation
     */
    updateTime?: Date | null;
}
