/* tslint:disable */
/* eslint-disable */
/**
 * HiGenious 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/HiGenious/'>https://gitee.com/zuohuaijun/HiGenious</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WmsAsnDetailDto } from './wms-asn-detail-dto';
 /**
 * 
 *
 * @export
 * @interface WmsAsnUpdateInput
 */
export interface WmsAsnUpdateInput {

    /**
     * @type {number}
     * @memberof WmsAsnUpdateInput
     */
    id?: number;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    asnNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    sysNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsAsnUpdateInput
     */
    customerId?: number | null;

    /**
     * @type {number}
     * @memberof WmsAsnUpdateInput
     */
    warehouseId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    orgId?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    vendorNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    vendorSiteCode?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAsnUpdateInput
     */
    shippedDate?: Date | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    customerNumber?: string | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    customerName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAsnUpdateInput
     */
    expectTime?: Date | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    batchNumber?: string | null;

    /**
     * @type {number}
     * @memberof WmsAsnUpdateInput
     */
    status?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    asnType?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAsnUpdateInput
     */
    completeTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsAsnUpdateInput
     */
    isConcession?: number;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    remark?: string | null;

    /**
     * @type {number}
     * @memberof WmsAsnUpdateInput
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    createUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAsnUpdateInput
     */
    createTime?: Date | null;

    /**
     * @type {number}
     * @memberof WmsAsnUpdateInput
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof WmsAsnUpdateInput
     */
    updateUserName?: string | null;

    /**
     * @type {Date}
     * @memberof WmsAsnUpdateInput
     */
    updateTime?: Date | null;

    /**
     * @type {Array<WmsAsnDetailDto>}
     * @memberof WmsAsnUpdateInput
     */
    asnDetails?: Array<WmsAsnDetailDto> | null;
}
