import Entity from './entity'
import mMSReceiptDetail from './mMSReceiptDetail'
// import AbpBase from "../../lib/abpbase";
export default class mReceiptReceivingDetail extends Entity<number>{
  
tenantId:number;
receiptReceivingId:number;
receiptId:number;
receiptDetailId:number;
receiptNumber:string;
receiptReceivingNumber:string;
purchaseOrderNumber:string;
externReceiptNumber:string;
supplierId
supplierName:string;
warehouseId
warehouseName:string;
lineNumber:string;
sKU:string;
uPC:string;
goodsType:string;
goodsName:string;
boxCode:string;
trayCode:string;
batchCode:string;
lotCode:string;
poCode:string;
weight:number;
volume:number;
expectedQty:number;
receivedQty:number;
receiptQty:number;
unitCode:string;
onwer:string;
area:string;
location:string;
goodsStatus:number;
productionDate:string;
expirationDate:string;
remark:string;
creator:string;
creationTime:string;
updator:string;
updateTime:string;
str1:string;
str2:string;
str3:string;
str4:string;
str5:string;
str6:string;
str7:string;
str8:string;
str9:string;
str10:string;
str11:string;
str12:string;
str13:string;
str14:string;
str15:string;
str16:string;
str17:string;
str18:string;
str19:string;
str20:string;
dateTime1:string;
dateTime2:string;
dateTime3:string;
dateTime4:string;
dateTime5:string;
int1:number;
int2:number;
int3:number;
int4:number;
int5:number;
    
}