import { number } from 'echarts'
import Entity from './entity'
export default class wxpressConfig extends Entity<number>{
 
customerId:number;
customerName:string;
warehouseId:number;
warehouseName:string;
expressCode:string;
expressCompany:string;
url:string;
urlToken:string;
appKey:string;
companyCode:string;
sign:string;
customerCode:string;
partnerId:string;
checkword:string;
clientId:string;
version:string;
templateCode:string;
password:string;
monthAccount:string;
env:string;
status:number;
creator:string;
creationTime:string;
updator:string;
updateTime:string;
str1:string;
str2:string;
str3:string;
str4:string;
str5:string;
str6:string;
str7:string;
str8:string;
str9:string;
str10:string;
str11:string;
str12:string;
str13:string;
str14:string;
str15:string;
str16:string;
str17:string;
str18:string;
str19:string;
str20:string;
dateTime1:string;
dateTime2:string;
dateTime3:string;
dateTime4:string;
dateTime5:string;
}